apiVersion: v1
kind: Pod
metadata:
  name: bastion
  labels:
    role: bastion
spec:
  containers:
  - name: bastion
    image: curlimages/curl
    imagePullPolicy: IfNotPresent
    command: ["sleep", "infinity"]        # Контейнер «спить» і чекає на наші команди exec